//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Litz.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int Id { get; set; }
        public System.DateTime Period { get; set; }
        public string Description { get; set; }
        public int GroupId { get; set; }
        public int UserId { get; set; }
        public int Amount { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
